### ISSUE TITLE
Reqeust for additions & random qeustions

### ISSUE THREAD

**Issue by AngryDan** [Hedrauta/Wreckfest-eventloop-randomizer#4]
Hey Brother,

First off great work on the script its a thing of beauty really.
My server visitors love the randomness of the tracks
But i have a few things i don't really understand,
1st is i cant get any demolition tracks in the random generator and as far as i understand its not implemented, if at all possible could you maybe add these to the script?
I would do it myself if i could but my knowledge of powershell is very limited.
2nd is that when im done running the script it tells me that all maps are empty and if i want to reload them but it does generate a .txt with the tracks. I'm confused :( 
3rd is that the script is divided in multiple sections of racing tracks but i don't understand what the difference is in the sections, they all seem to be races maybe you did this for race options like elimination and normal races? please can you help me out here?

many thanks in any case
:)

**Comment by Hedrauta** [comment]
oof... 2 weeks ago... should look into my GitHub too ^.^ 
Well then.... 

1.
Demolition-modes are enabled.... their maps are just not available in a file in this git... will upload a demo-maps-text-file after implementing the new Racing map

2.
Well... they are not "exactly" emptied.... I'm loading the map-files into an array, which is then my "txt-file"... so the original files will be unharmed... ( so you can run the script multiple times for different servers )
When a Map-array did go empty, it will ask you for reload, if denying, it will skip that array until the end. 
The Result of the whole "eventloop-randomizing" will get written into the eventloop.txt-file, which can also be copied into your Clipboard at the end of the script... I can't write the whole config for you ;) That's what you have to do on your own ;)

3. The current "separation" is 

- Special.txt: Rockfield Roughspot ( should be oval, but I like it as a special one) Deathloop, CrashCanyon, Hellride, etc
- Oval.txt: all other Oval-Tracks than Rockfield
- figure8.txt: Self-explained
- racing_s.txt: short tracks, length < 1.2 km
- racing.txt: tracks between 1.2 km and 1.8 km
- racing_l.txt: length >1.8 

i sorted them like this, because i tried to get an average length of 8-10 km per tracks on racing ones.... Special, ovals and figure8 were ..... like i wanted them

My best suggestion: write your own files.... grab the map-names ( like they were written in the txt-files) , sort them it into your own "category"-files, and run the script
that's how i designed the script... ;)

Oh... and sorry for that late response... Git didn't mail me an issue -.-

Sincere, [Hedrauta](http://community.bugbeargames.com/threads/tool-wreckfester-the-wreckfest-eventloop-randomizer-script.14758/)

**Comment by Hedrauta** [comment]
https://github.com/Hedrauta/Wreckfest-eventloop-randomizer/commit/c7cfc9f00259ece08508aed0899e3594fbfdd896
And new update is live 😉
